version: '3'
services:
  bandot-node:
    build:
      context: .
    ports:
      - "127.0.0.1:30333:30333/tcp"
      - "127.0.0.1:9933:9933/tcp"
    image: bandot/bandot:latest
    volumes:
      - "bandot-data:/data"
    command: bandot-node

volumes:
  bandot-data: